name: 'Bake AMI Workflow'
description: 'Orchestrates the AMI baking process using bk-bake-ami'
inputs:
  ami_name:
    description: 'AMI name filter'
    required: true
    default: 'al2023-ami-2023*-kernel-6.1-x86_64'
  ami_owner:
    description: 'AMI owner'
    required: true
    default: 'amazon'
  ami_architecture:
    description: 'AMI architecture'
    required: true
    default: 'x86_64'
  ami_os_type:
    description: 'AMI OS type'
    required: true
    default: 'linux'
  role_to_assume:
    description: 'The ARN of the IAM role to assume (pass secret here)'
    required: true
  baking_recipe_playbook:
    description: 'The path to the baking recipe playbook'
    required: true
  application_name:
    description: 'The name of the application'
    required: true

outputs:
  ami_id:
    description: 'The ID of the baked AMI'
    value: ${{ steps.bake.outputs.ami_id }}
  ami_name:
    description: 'The name of the baked AMI'
    value: ${{ steps.bake.outputs.ami_name }}
  ami_arn:
    description: 'The ARN of the baked AMI'
    value: ${{ steps.bake.outputs.ami_arn }}

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Display role to assume
      run: echo "Assuming role ${{ inputs.role_to_assume }}"
      shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_to_assume }}
        aws-region: 'us-east-1'

    - name: Bake AMI
      id: bake
      shell: bash
      # Terraform variables are passed using the TF_VAR_<variable_name> environment variables.
      # These environment variables map directly to the variables defined in terraform/variables.tf
      # and are accessible inside terraform/main.tf via var.<variable_name>.
      env:
        TF_VAR_ami_name: ${{ inputs.ami_name }}
        TF_VAR_ami_owner: ${{ inputs.ami_owner }}
        TF_VAR_ami_architecture: ${{ inputs.ami_architecture }}
        TF_VAR_ami_os_type: ${{ inputs.ami_os_type }}
        TF_VAR_baking_recipe_playbook: ${{ inputs.baking_recipe_playbook }}
        TF_VAR_application_name: ${{ inputs.application_name }}
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve

        echo "ami_id=$(terraform output -raw ami_id)" >> $GITHUB_OUTPUT
        echo "ami_name=$(terraform output -raw ami_name)" >> $GITHUB_OUTPUT
        echo "ami_arn=$(terraform output -raw ami_arn)" >> $GITHUB_OUTPUT


    - name: Display Fetch AMI ID and AMT Name
      if: success()
      run: |
        echo "AMI ID is ${{ steps.bake.outputs.ami_id }}"
        echo "AMI NAME is ${{ steps.bake.outputs.ami_name }}"
      shell: bash
