name: 'Bake AMI Workflow'
description: 'Orchestrates the AMI baking process using bk-bake-ami'
inputs:
  ami_name:
    description: 'AMI name filter'
    required: true
    default: 'al2023-ami-2023*-kernel-6.1-x86_64'
  ami_owner:
    description: 'AMI owner'
    required: true
    default: 'amazon'
  ami_architecture:
    description: 'AMI architecture'
    required: true
    default: 'x86_64'
  ami_os_type:
    description: 'AMI OS type'
    required: true
    default: 'linux'
  role_to_assume:
    description: 'The ARN of the IAM role to assume (pass secret here)'
    required: true

outputs:
  ami_id:
    description: 'The ID of the baked AMI'
    value: ${{ steps.bake.outputs.ami_id }}
  ami_name:
    description: 'The name of the baked AMI'
    value: ${{ steps.bake.outputs.ami_name }}
  ami_arn:
    description: 'The ARN of the baked AMI'
    value: ${{ steps.bake.outputs.ami_arn }}

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Display role to assume
      run: echo "Assuming role ${{ inputs.role_to_assume }}"
      shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_to_assume }}
        aws-region: 'us-east-1'

    - name: test aws credentials
      run: aws sts get-caller-identity
      shell: bash

    - name: Get Latest AMI
      id: bake
      uses: BakeFoundry/bk-bake-ami-module@v1
      with:
        ami_name: ${{ inputs.ami_name }}
        ami_owner: ${{ inputs.ami_owner }}
        ami_architecture: ${{ inputs.ami_architecture }}
        ami_os_type: ${{ inputs.ami_os_type }}

    - name: Display Fetch AMI ID and AMT Name
      run: |
        echo "AMI ID is ${{ steps.bake.outputs.ami_id }}"
        echo "AMI NAME is ${{ steps.bake.outputs.ami_name }}"
      shell: bash
